name: Semgrep
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0
permissions:
  contents: read
jobs:
  semgrep:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep scan (latest, tokenless)
        run: |-
          python -m pip install --upgrade semgrep
          semgrep scan --config p/ci --sarif --output semgrep.sarif || true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
        if: always()
